---
name: setup
description: Common tasks for preparing the environment

runs:
  using: "composite"
  steps:
      - uses: actions/setup-go@v6
        if: runner.os != 'Windows'
        with:
          go-version-file: go.mod
          cache: true
      # See https://github.com/actions/setup-go/pull/515
      - uses: antontroshin/setup-go@bda02de8887c9946189f81e7e59512914aeb9ea4
        if: runner.os == 'Windows'
        with:
          go-version-file: go.mod
          cache: true
      - name: install mage
        run: go install github.com/magefile/mage
        shell: 'bash'
