# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  SETUP_GOLANG_VERSION: '1.18.10'

steps:
  - label: "Update"
    key: update
    command:
      - ".buildkite/scripts/update-test.sh"
    agents:
      image: "golang:${SETUP_GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"
    artifact_paths:
      - "junit-*.xml"

  - label: ":junit: Junit annotate"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "junit-*.xml"
          fail-build-on-error: true
    agents:
      provider: "gcp" #junit plugin requires docker
    depends_on:
      - step: "update"
        allow_failure: true
