# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  SETUP_GOLANG_VERSION: '1.21.8'

steps:
  - group: "Linux"
    steps:
    - label: "Linux: Unit Tests"
      key: update-linux
      command:
        - ".buildkite/scripts/update-test.sh"
      agents:
        image: "golang:${SETUP_GOLANG_VERSION}"
        cpu: "8"
        memory: "4G"
      artifact_paths:
        - "junit-*.xml"

    - label: "Linux: Lint"
      key: lint-linux
      command:
        - ".buildkite/scripts/lint.sh"
      agents:
        image: "golang:${SETUP_GOLANG_VERSION}"
        cpu: "8"
        memory: "4G"

    - label: ":junit: Linux: Junit annotate"
      plugins:
        - junit-annotate#v2.4.1:
            artifacts: "junit-*.xml"
            fail-build-on-error: true
      agents:
        provider: "gcp" #junit plugin requires docker
      depends_on:
        - step: update-linux
          allow_failure: true

  - group: "Windows"
    steps:
      - label: "Windows: Unit Tests"
        key: update-windows
        command: |
          .buildkite/scripts/update-test.ps1
        agents:
          provider: "gcp"
          machineType: "n1-standard-8"
          image: "family/platform-ingest-elastic-agent-windows-2022"
        artifact_paths:
          - "junit-*.xml"

      - label: "Windows: Lint"
        key: lint-windows
        command: |
          mage -debug check
          go vet ./...
        agents:
          provider: "gcp"
          machineType: "n1-standard-8"
          image: "family/platform-ingest-elastic-agent-windows-2022"
        artifact_paths:
          - "junit-*.xml"

      - label: ":junit: Windows: Junit annotate"
        plugins:
          - junit-annotate#v2.4.1:
              artifacts: "junit-*.xml"
              fail-build-on-error: true
        agents:
          provider: "gcp" #junit plugin requires docker
        depends_on:
          - step: update-windows
            allow_failure: true