#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent { label 'ubuntu && immutable' }
  environment {
    BASE_DIR="src/github.com/elastic/elastic-agent-client"
    PIPELINE_LOG_LEVEL='INFO'
    PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin" 
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
    quietPeriod(10)
  }
  triggers {
    issueCommentTrigger('(?i).*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*')
  }
  stages {
    stage('Checkout') {
      options { skipDefaultCheckout() }
      steps {
        pipelineManager([ cancelPreviousRunningBuilds: [ when: 'PR' ] ])
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}")
        sh 'command -v docker'
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Lint') {
      agent {
        dockerfile {
          dir ".ci/jenkins-go-agent"
        }
      }
      environment{
        HOME = "${env.WORKSPACE}/${env.BASE_DIR}"
        GOPATH = "${env.WORKSPACE}"
      }
      steps {
        deleteDir()
        unstash 'source'
        dir("${BASE_DIR}"){
          sh(label: 'Checks formatting / linting',script: 'mage -debug check:all')
        }
      }
    }
    stage('Update') {
      agent {
        dockerfile {
          dir ".ci/jenkins-go-agent"
        }
      }
      environment{
        HOME = "${env.WORKSPACE}/${env.BASE_DIR}"
        GOPATH = "${env.WORKSPACE}"
      }
      steps {
        deleteDir()
        unstash 'source'
        dir("${BASE_DIR}"){
          sh(label: 'Checks formatting / linting',script: 'mage -debug update')
        }
      }
    }
    stage('Test') {
      agent {
        dockerfile {
          dir ".ci/jenkins-go-agent"
        }
      }
      environment{
        HOME = "${env.WORKSPACE}/${env.BASE_DIR}"
        GOPATH = "${env.WORKSPACE}"
      }
      steps {
        deleteDir()
        unstash 'source'
        dir("${BASE_DIR}"){
          sh(label: 'Unit test', script: 'go test ./... 2>&1 | tee test_results.txt')
          sh(label: 'Convert test results', script: 'go-junit-report < test_results.txt > junit.xml')
        }
      }
      post {
        always {
          junit(allowEmptyResults: true,
            keepLongStdio: true,
            testResults: "${BASE_DIR}/junit*.xml")
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult(prComment: true)
    }
  }
}
