// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by "stringer -type=ChangeType -linecomment -output client_v2_strings.go"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChangeUnitAdded-0]
	_ = x[ChangeUnitModified-1]
	_ = x[ChangeUnitRemoved-2]
	_ = x[ChangeFeatureModified-3]
}

const _ChangeType_name = "unit_addedunit_modifiedunit_removedfeature_modified"

var _ChangeType_index = [...]uint8{0, 10, 23, 35, 51}

func (i ChangeType) String() string {
	if i < 0 || i >= ChangeType(len(_ChangeType_index)-1) {
		return "ChangeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangeType_name[_ChangeType_index[i]:_ChangeType_index[i+1]]
}
