// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by "stringer -type=ChangeType,Trigger -linecomment -output client_v2_strings.go"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnitChangedAdded-0]
	_ = x[UnitChangedModified-1]
	_ = x[UnitChangedRemoved-2]
}

const _ChangeType_name = "unit_addedunit_modifiedunit_removed"

var _ChangeType_index = [...]uint8{0, 10, 23, 35}

func (i ChangeType) String() string {
	if i < 0 || i >= ChangeType(len(_ChangeType_index)-1) {
		return "ChangeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangeType_name[_ChangeType_index[i]:_ChangeType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TriggeredNothing-0]
	_ = x[TriggeredConfigChange-2]
	_ = x[TriggeredFeatureChange-4]
	_ = x[TriggeredLogLevelChange-8]
	_ = x[TriggeredStateChange-16]
}

const (
	_Trigger_name_0 = "nothing_triggered"
	_Trigger_name_1 = "config_change_triggered"
	_Trigger_name_2 = "feature_change_triggered"
	_Trigger_name_3 = "log_level_triggered"
	_Trigger_name_4 = "state_change_triggered"
)

func (i Trigger) String() string {
	switch {
	case i == 0:
		return _Trigger_name_0
	case i == 2:
		return _Trigger_name_1
	case i == 4:
		return _Trigger_name_2
	case i == 8:
		return _Trigger_name_3
	case i == 16:
		return _Trigger_name_4
	default:
		return "Trigger(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
